[tool.poetry]
name = "inference"
version = "0.1.0"
description = ""
authors = ["Lucas Ikuhara <ikuhara@ibm.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
ollama = "^0.4.7"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
